// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oficina.Estoque.Infrastructure.Data;

#nullable disable

namespace Oficina.Estoque.Infrastructure.Migrations
{
    [DbContext(typeof(EstoqueDbContext))]
    [Migration("20251016133825_AddPecaSeedWithDate")]
    partial class AddPecaSeedWithDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oficina.Estoque.Domain.Entities.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PecaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("TipoMovimento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("Oficina.Estoque.Domain.Entities.Peca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeMinima")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Pecas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Codigo = "FILTRO-001",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Filtro de óleo sintético para motores 1.0 a 2.0",
                            Fabricante = "Bosch",
                            Nome = "Filtro de óleo",
                            Preco = 45.90m,
                            Quantidade = 10,
                            QuantidadeMinima = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Codigo = "PAST-FREIO-002",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Pastilha de freio dianteira para veículos leves",
                            Fabricante = "TRW",
                            Nome = "Pastilha de freio",
                            Preco = 120.00m,
                            Quantidade = 8,
                            QuantidadeMinima = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Codigo = "OLEO-5W30-003",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Óleo lubrificante sintético 5W30",
                            Fabricante = "Mobil",
                            Nome = "Óleo 5W30",
                            Preco = 32.50m,
                            Quantidade = 20,
                            QuantidadeMinima = 5,
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Codigo = "FILTRO-AR-004",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Filtro de ar para motores flex",
                            Fabricante = "Mann",
                            Nome = "Filtro de ar",
                            Preco = 38.00m,
                            Quantidade = 6,
                            QuantidadeMinima = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Codigo = "COR-DENT-005",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Correia dentada para motores 1.6",
                            Fabricante = "Gates",
                            Nome = "Correia dentada",
                            Preco = 85.00m,
                            Quantidade = 4,
                            QuantidadeMinima = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Codigo = "VELA-IGN-006",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Vela de ignição para motores flex",
                            Fabricante = "NGK",
                            Nome = "Vela de ignição",
                            Preco = 22.00m,
                            Quantidade = 16,
                            QuantidadeMinima = 4,
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Codigo = "AMORT-D-007",
                            DataAtualizacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Amortecedor dianteiro para veículos compactos",
                            Fabricante = "Monroe",
                            Nome = "Amortecedor dianteiro",
                            Preco = 210.00m,
                            Quantidade = 2,
                            QuantidadeMinima = 2,
                            Tipo = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
